name: mirror
on:
  push:
    branches: [dev, master]

jobs:
  mirror-to-gitee:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITEE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
    - name: Mirror to Gitee
      run: |
        git clone --mirror "git@github.com:eesast/THUAI5.git" THUAI5 && cd THUAI5
        git remote set-url --push origin "git@gitee.com:eesast/thuai5.git"
        git fetch -p origin
        git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
        git push --mirror
